pipeline{
	agent any
	
	stages{
		stage('check stage'){
			steps{
			withMaven(maven: 'Mvn'){
				bat 'mvn --version'
			
			}
			}
		
		}
		
		stage('compile stage'){
			steps{
			withMaven(maven: 'Mvn'){
				bat 'mvn -f mvn-demo/pom.xml compile'
				}
			}
		
		}
		
		stage('Test stage'){
			steps{
			withMaven(maven: 'Mvn'){
				bat 'mvn -f mvn-demo/pom.xml install'
				} 
			}
		
		}
	}
}