pipeline{
	agent any
	
	stages{
		stage('check stage'){
			steps{
			withMaven(maven: 'mvn'){
				bat 'mvn --version'
			
			}
			}
		
		}
		
		stage('compile stage'){
			steps{
			withMaven(maven: 'mvn'){
				bat 'mvn -f mvn-demo/pom.xml clean compile'
				}
			}
		
		}
		
		stage('Test stage'){
			steps{
			withMaven(maven: 'mvn'){
				bat 'mvn  -f mvn-demo/pom.xml test'
				} 
			}
		
		}
	}
}